version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gold
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
